# Form implementation generated from reading ui file 'C:\Users\Admin\PyQt6\cau1\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\PyQt6\\cau1\\img/loan_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_loan_amount = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_loan_amount.setObjectName("label_loan_amount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_loan_amount)
        self.lineEdit_loan_amount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_loan_amount.setObjectName("lineEdit_loan_amount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_loan_amount)
        self.label_interest_rate = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_interest_rate.setObjectName("label_interest_rate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_interest_rate)
        self.lineEdit_interest_rate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_interest_rate.setObjectName("lineEdit_interest_rate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_interest_rate)
        self.label_loan_duration = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_loan_duration.setObjectName("label_loan_duration")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_loan_duration)
        self.lineEdit_loan_duration = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_loan_duration.setObjectName("lineEdit_loan_duration")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_loan_duration)
        self.verticalLayout.addLayout(self.formLayout)
        self.button_calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\PyQt6\\cau1\\img/calculate_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_calculate.setIcon(icon1)
        self.button_calculate.setObjectName("button_calculate")
        self.verticalLayout.addWidget(self.button_calculate)
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.button_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\PyQt6\\cau1\\img/clear_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_clear.setIcon(icon2)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_buttons.addWidget(self.button_clear)
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Admin\\PyQt6\\cau1\\img/exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_exit.setIcon(icon3)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout_buttons.addWidget(self.button_exit)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tính Khoản Thanh Toán Hàng Tháng"))
        self.centralwidget.setStyleSheet(_translate("MainWindow", "\n"
"     QWidget {\n"
"         background-color: #f0f4f8;\n"
"     }\n"
"     QLabel#label_title {\n"
"         font-size: 18pt;\n"
"         font-weight: bold;\n"
"         color: #2b2d42;\n"
"     }\n"
"     QLabel {\n"
"         font-size: 10pt;\n"
"         color: #2b2d42;\n"
"     }\n"
"     QLineEdit {\n"
"         background-color: #ffffff;\n"
"         border: 1px solid #8d99ae;\n"
"         padding: 6px;\n"
"         border-radius: 5px;\n"
"     }\n"
"     QPushButton {\n"
"         background-color: #8d99ae;\n"
"         color: #ffffff;\n"
"         padding: 10px;\n"
"         font-size: 12pt;\n"
"         font-weight: bold;\n"
"         border-radius: 5px;\n"
"     }\n"
"     QPushButton:hover {\n"
"         background-color: #2b2d42;\n"
"     }\n"
"     QLabel#label_result {\n"
"         font-size: 12pt;\n"
"         color: #ef233c;\n"
"         font-weight: bold;\n"
"     }\n"
"    "))
        self.label_title.setText(_translate("MainWindow", "Tính Khoản Thanh Toán Hàng Tháng"))
        self.label_loan_amount.setText(_translate("MainWindow", "Số tiền vay:"))
        self.label_interest_rate.setText(_translate("MainWindow", "Lãi suất hàng năm (%):"))
        self.label_loan_duration.setText(_translate("MainWindow", "Thời hạn vay (năm):"))
        self.button_calculate.setText(_translate("MainWindow", "Tính Khoản Thanh Toán"))
        self.label_result.setText(_translate("MainWindow", "Kết quả sẽ hiển thị tại đây."))
        self.button_clear.setText(_translate("MainWindow", "Xóa"))
        self.button_exit.setText(_translate("MainWindow", "Thoát"))
